//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspTry_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class birimler
    {
        public int birimID_ { get; set; }
        public string birimAdi { get; set; }
    }
}
