//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspTry_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public string kulAdi { get; set; }
        public string sifre { get; set; }
        public string AdSoyad { get; set; }
        public string birim { get; set; }
        public string yetki { get; set; }
        public string foto { get; set; }
    }
}
